// Fetch the Google Fonts we use and save them under ./fonts as woff2
// files + a self-hosted @font-face stylesheet. The Android APK and the
// PWA both ship these files locally so the first paint doesn't depend
// on network — critical for offline app opens where blocking on a
// render-blocking Google Fonts stylesheet leaves the WebView white
// for the length of the DNS/HTTP timeout.
//
// Idempotent: re-running overwrites the same files. Only need to re-
// run when we add/remove a weight or family in css/styles.css.
//
// Uses a Chrome UA when fetching the CSS index so Google serves woff2
// URLs (older/generic UAs get truetype). The woff2 downloads are then
// pulled with no UA header — Google's font CDN doesn't care.

import fs from 'node:fs';
import path from 'node:path';
import https from 'node:https';

const ROOT   = path.resolve('.');
const OUTDIR = path.join(ROOT, 'fonts');
fs.mkdirSync(OUTDIR, { recursive: true });

// The exact families/weights that css/styles.css references. If you
// add a font-weight or family, add it here too and re-run.
//
// Anton is a single-weight display font (400 only).
// Fraunces is only used at italic 400 (see .tagline etc).
// JetBrains Mono uses 400/500/600/700.
// Manrope uses 400/500/600/700.
//
// display=swap so if the font is somehow slow, system fallback shows
// immediately and gets swapped when the woff2 arrives.
const CSS_URL =
  'https://fonts.googleapis.com/css2' +
  '?family=Anton' +
  '&family=Fraunces:ital,wght@1,400' +
  '&family=JetBrains+Mono:wght@400;500;600;700' +
  '&family=Manrope:wght@400;500;600;700' +
  '&display=swap';

const CHROME_UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36';

function get(url, headers = {}) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers }, res => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        return get(res.headers.location, headers).then(resolve, reject);
      }
      if (res.statusCode !== 200) {
        return reject(new Error(`${url} → HTTP ${res.statusCode}`));
      }
      const chunks = [];
      res.on('data', c => chunks.push(c));
      res.on('end',  () => resolve(Buffer.concat(chunks)));
    }).on('error', reject);
  });
}

console.log('Fetching Google Fonts CSS index…');
const cssBuf = await get(CSS_URL, { 'User-Agent': CHROME_UA });
const css    = cssBuf.toString('utf8');

// Google splits each family into per-subset @font-face blocks (latin,
// latin-ext, cyrillic, greek, vietnamese, …). We only need the
// unicode-range starting at U+0000-00FF for basic Latin — the app is
// English-only. Keep the latin-ext block too so we don't drop the
// long em-dash / accented characters that show up in user chain names.
//
// A block looks like:
//   /* latin */
//   @font-face { font-family: 'Anton'; font-style: normal; font-weight: 400;
//     src: url(https://fonts.gstatic.com/…/xxx.woff2) format('woff2');
//     unicode-range: U+0000-00FF, U+0131, …; }
const KEEP = new Set(['latin', 'latin-ext']);
const blocks = [];
const BLOCK_RE = /\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]+\})/g;
let m;
while ((m = BLOCK_RE.exec(css)) !== null) {
  if (!KEEP.has(m[1])) continue;
  blocks.push({ subset: m[1], text: m[2] });
}
if (!blocks.length) {
  console.error('No @font-face blocks matched — Google CSS format may have changed.');
  process.exit(1);
}
console.log(`Matched ${blocks.length} @font-face blocks across ${KEEP.size} subsets.`);

// Rewrite each block to point at a local file. Slug: family + weight
// + style + subset + short URL hash so re-runs are stable across
// filename changes on Google's side.
function slug(fam, weight, style, subset) {
  const base = fam.replace(/[^a-z0-9]+/gi, '-').toLowerCase();
  const w    = weight || '400';
  const s    = style === 'italic' ? '-italic' : '';
  return `${base}-${w}${s}-${subset}.woff2`;
}
function pick(re, s) { const mm = s.match(re); return mm && mm[1]; }

let out = '/* Self-hosted Google Fonts — generated by tools/fetch-fonts.mjs. Do not edit. */\n\n';
let totalBytes = 0;

for (const b of blocks) {
  const family = pick(/font-family:\s*'([^']+)'/, b.text);
  const weight = pick(/font-weight:\s*(\d+)/, b.text) || '400';
  const style  = pick(/font-style:\s*([a-z]+)/, b.text) || 'normal';
  const srcUrl = pick(/url\((https:\/\/[^)]+)\)/, b.text);
  const range  = pick(/unicode-range:\s*([^;]+);/, b.text);
  if (!family || !srcUrl) {
    console.warn('Skipping malformed block:', b.text.slice(0, 80));
    continue;
  }
  const file  = slug(family, weight, style, b.subset);
  const local = path.join(OUTDIR, file);
  console.log(`  ${family} ${weight}${style === 'italic' ? 'i' : ''} [${b.subset}] → ${file}`);
  const buf = await get(srcUrl);
  fs.writeFileSync(local, buf);
  totalBytes += buf.length;
  out += `@font-face {\n` +
         `  font-family: '${family}';\n` +
         `  font-style: ${style};\n` +
         `  font-weight: ${weight};\n` +
         `  font-display: swap;\n` +
         `  src: url('../fonts/${file}') format('woff2');\n` +
         (range ? `  unicode-range: ${range};\n` : '') +
         `}\n\n`;
}

const cssOut = path.join(ROOT, 'css', 'fonts.css');
fs.writeFileSync(cssOut, out);
console.log(`\n✓ ${blocks.length} woff2 files (${(totalBytes / 1024).toFixed(1)} KB) → ${OUTDIR}`);
console.log(`✓ Self-hosted @font-face stylesheet → ${cssOut}`);
